Alpha
codex-team/codex.notes.server pull request #1
Opened 2017-10-12 17:06 UTC by demyashev

Project initialization

2017-10-12 18:04 UTC, neSpecc requested changes

2017-10-12 18:04 UTC, neSpecc commented on src/models/User.php
> +                # user init fault
нужно залогировать ошибку

2017-10-12 18:04 UTC, neSpecc commented on src/models/User.php
> +
лог

2017-10-12 18:04 UTC, neSpecc commented on src/modules/Auth.php
> +        if (!$localSalt)
скобки {}

2017-10-12 18:04 UTC, neSpecc commented on src/public/routes.php
> + * @return  JSON
предлагаю к методам апи подробно описывать возвращаемый объект

2017-10-12 18:04 UTC, neSpecc commented on src/public/routes.php
> +$app->post('/user/get/{userId}', function(Request $request, Response $response) {
ко всем методам надо описать доки

2017-10-13 08:26 UTC, n0str requested changes

2017-10-13 08:26 UTC, n0str commented on src/models/User.php
> +
лог

2017-10-13 08:26 UTC, n0str commented on src/modules/Auth.php
> +        if (!$lenght)
скобки {}

2017-10-13 08:26 UTC, n0str commented on src/modules/Auth.php
> +    public static function generatePassword(int $lenght = 0)
length

2017-10-13 08:26 UTC, n0str commented on src/modules/Auth.php
> +        return substr(md5(uniqid()), 0, $lenght);
length

2017-10-13 08:26 UTC, n0str commented on src/modules/Auth.php
> +        return substr(md5(uniqid()), 0, $lenght);
Плохой способ генерации пароля. Используй стандартные методы random_bytes() и прочее.

2017-10-13 08:48 UTC, talyguryn requested changes

2017-10-13 08:48 UTC, talyguryn commented on src/models/User.php
> +    public function __construct(string $userId = '')
`string` тип точно нужно указывать?

2017-10-13 08:48 UTC, talyguryn commented on src/models/User.php
> +                # user init fault
взгляни на https://github.com/katzgrau/KLogger
потом подключим сюда Хоук

2017-10-13 08:48 UTC, talyguryn commented on src/models/User.php
> +
лог

2017-10-13 08:48 UTC, talyguryn commented on src/modules/Auth.php
> +        return substr(md5(uniqid()), 0, $lenght);
вчера обсуждали, что uniqid норм

2017-10-13 08:48 UTC, talyguryn commented on src/public/routes.php
> +    global $messages;
не могу найти, где ты задаешь это

2017-10-14 15:12 UTC, demyashev commented on src/modules/Auth.php
> +    public static function generatePassword(int $lenght = 0)
[x]

2017-10-14 15:14 UTC, demyashev commented on src/modules/Auth.php
> +        return substr(md5(uniqid()), 0, $lenght);
@n0str так я же переписывал node.js сервер на php идентично :)

2017-10-14 15:16 UTC, demyashev commented on src/models/User.php
> +    public function __construct(string $userId = '')
@talyguryn Идея инициализировать коллекцию по идентификатору. Если принимать не строку а объект, то...мы уже имеем объект, чего нам там еще надо инициализировать

2017-10-14 18:02 UTC, gohabereg requested changes

2017-10-14 18:02 UTC, gohabereg commented on README.md
> +{"success":true,"result":{"_id":{"$oid":"59de92565d945f103933fd82"},"user_id":"89c2633b","password":{"hash":"5195c9ef71d1d26ffc0ff2832f9bf286eb574e8d7826ebd9f94f3d1ad19ad68f","localSalt":"1090dda9"},
Может `_id` сразу строкой делать?

2017-10-14 18:02 UTC, gohabereg commented on src/models/User.php
> +            return ['uid' => $userId];
А пароль не надо вернуть?

2017-10-14 18:02 UTC, gohabereg commented on src/modules/Auth.php
> +        if (!$userId || $password) {
Кажется, забыл `!`

2017-10-14 18:02 UTC, gohabereg commented on src/public/routes.php
> +    global $messages;
в конфигах

2017-10-14 18:02 UTC, gohabereg commented on src/public/routes.php
> +$app->post('/user/create', function(Request $request, Response $response) {
Надо бы выносить сами обработчики в отдельные контроллеры

2017-10-15 19:23 UTC, closed without merging