Issue 51
codex-team/codex.notes.server pull request #10
Opened 2017-11-19 19:56 UTC by demyashev

Действия с папками
Записей нет

issue #9 проверял, его сейчас нет. Видать была ошибка на предыдущей версии

2017-11-21 18:18 UTC, n0str approved these changes

2017-11-23 18:12 UTC, n0str requested changes
Комменты ко всем функциям и рефакторинг отдельным issue? или допилишь сегодня?

2017-11-23 18:12 UTC, n0str commented on www/versions/v1/models/Mongo.php
> +            $message = sprintf($this->messages['collection']['create']['error'], $collection, $e->getMessage());
что это?

2017-12-01 15:17 UTC, talyguryn requested changes

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/Api.php
> +    public  function getFolder()
убрать лишний пробел между `public` и `function`

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/Api.php
> +    public  function getFolder()
добавь коммент к функции

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/Api.php
>      public function getResponse()
добавь коммент к функции

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/Api.php
>      public function getResponse()
эта функция выполняется примерно то же, что и `getDefaultResponseAsArray`. почему бы не вызывать ту внутри этой

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/api/Folder.php
> +     *
не все параметры описаны

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/api/Folder.php
> +     *
где параметры?

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/api/Note.php
> +     * @param $user     User id
опиши параметры этой функции

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/api/Note.php
> +     *
где параметры?

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/controllers/Folder.php
> +     * Получаем пользователя
напиши нормальный коммент к этой функции

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/models/Folder.php
> +    public function create(string $user = '', string $name = '', string $id = '', int $timestamp = 0 )
добавь коммент к функции

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/models/Folder.php
> +    public function delete(string $user = '', string $id = '')
добавь коммент к функции

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/models/Folders.php
> +    public function create(string $user = '', string $name = '', string $id = '', int $timestamp = 0)
добавь коммент к функции

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/models/Folders.php
> +    public function delete(string $user = '', string $id = '')
добавь коммент к функции

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/models/Mongo.php
> +    public function createCollection(string $collection = '', array $content = [])
добавь коммент к функции

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/models/Mongo.php
> +    public function deleteCollection(string $collection = '')
добавь коммент к функции

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/models/Mongo.php
> +    public function insert(string $collection = '', array $content = [])
добавь коммент к функции

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/models/Mongo.php
> +    public function deleteInCollection(string $collection = '', array $criteria = [])
добавь коммент к функции

2017-12-01 15:17 UTC, talyguryn commented on www/versions/v1/models/Mongo.php
> +    public function collectionIsset(string $collection = '')
добавь коммент к функции

2017-12-05 14:48 UTC, demyashev commented
Сегодня апдейтну

2017-12-05 16:16 UTC, demyashev commented
Действий с заметками нет. Надо написать модель 
www/versions/v1/models/Note.php

2017-12-05 16:19 UTC, talyguryn approved these changes

2017-12-05 16:21 UTC, khaydarov approved these changes

2017-12-05 16:24 UTC, demyashev commented on www/versions/v1/controllers/Folder.php
> +     * Получаем пользователя
Написал

2017-12-05 16:49 UTC, merged