Mutations
codex-team/codex.notes.server pull request #18
Opened 2017-12-21 15:53 UTC by talyguryn

2017-12-21 17:23 UTC, neSpecc requested changes

2017-12-21 17:23 UTC, neSpecc commented on www/components/api/models/Folder.php
> +    public $id;
нужно задокументировать свойства: описание и тип данных

2017-12-21 17:23 UTC, neSpecc commented on www/components/api/models/Folder.php
> +class Folder
нужно описать класс

2017-12-21 17:23 UTC, neSpecc commented on www/components/api/models/Folder.php
> +    public function __construct($data) {
не описан параметр data

2017-12-21 17:23 UTC, neSpecc commented on www/components/api/models/Folders.php
> +    public function __construct($userId)
нужно вернуть тип данных

2017-12-21 17:23 UTC, neSpecc commented on www/components/api/models/Folders.php
> +     * @throws
не задокументирована ошибка

2017-12-21 17:23 UTC, neSpecc commented on www/components/api/models/Folders.php
> +     * @throws
описание, тип

2017-12-21 17:23 UTC, neSpecc commented on www/components/api/models/Folders.php
> +    public function create($data)
: Folder

2017-12-21 17:23 UTC, neSpecc commented on www/components/api/models/Note.php
> +class Note
описание

2017-12-21 17:23 UTC, neSpecc commented on www/components/api/models/Note.php
> +    public $id;
описание, тип

2017-12-21 17:36 UTC, gohabereg requested changes

2017-12-21 17:36 UTC, gohabereg commented on www/components/api/models/Folder.php
> +            $this->$key = $value;
Проверку бы на наличие ключа

2017-12-21 17:36 UTC, gohabereg commented on www/components/api/models/Folders.php
> +        $this->mongo = new Mongo();
Может это в какой-нибудь абстрактный класс модели вынести?

2017-12-21 18:00 UTC, neSpecc requested changes

2017-12-21 18:00 UTC, neSpecc commented on www/components/api/Api.php
> +    public function graphql()
вернуть слимовские  Request $request, Response $response, $arg в параметры

2017-12-21 18:00 UTC, neSpecc commented on www/components/api/models/Folders.php
> +    public function rename($data)
:boolean

2017-12-21 18:00 UTC, neSpecc commented on www/components/api/models/Folders.php
> +     * Rename folder
задокументировать $data

2017-12-21 18:00 UTC, neSpecc commented on www/components/api/models/Folders.php
> +        $filter = ['_id' => new MongoId($data['id'])];
перенести строку

2017-12-21 18:00 UTC, neSpecc commented on www/components/api/models/Notes.php
> +    public function __construct($userId, $folderId)
добавить корректные типы

2017-12-21 18:00 UTC, neSpecc commented on www/components/api/models/Notes.php
> +    public function __construct($userId, $folderId)
и в описании параметров конструктора

2017-12-21 18:00 UTC, neSpecc commented on www/components/api/models/Notes.php
> +    private static function collection($userId, $folderId): string
вернуть типы, обновить в описании функции

2017-12-21 18:00 UTC, neSpecc commented on www/components/api/models/User.php
> +    public function __construct($id = null) {
тип

2017-12-21 18:00 UTC, neSpecc commented on www/components/base/models/Mongo.php
> +     * [$connection description]
описание

2017-12-21 18:00 UTC, neSpecc commented on www/schema/types/Mutation.php
> +                    'createFolder' => [
универсальная мутация folder

2017-12-21 18:00 UTC, neSpecc commented on www/schema/types/Mutation.php
> +                    'deleteFolder' => [
update is_removed = 1

2017-12-23 03:59 UTC, neSpecc requested changes

2017-12-23 03:59 UTC, neSpecc commented on www/components/api/models/Folder.php
> +        $mongoResponse = Mongo::connect()
не хочешь вернуть этот респонс? чтобы можно было вернуть ошибку или еще что-то. Если решишь добавить return, то не забудь указать тип возвращаемого значение и документацию

2017-12-23 03:59 UTC, neSpecc commented on www/components/base/models/Mongo.php
> +            $database = isset($_SERVER['MONGO_DBNAME']) ? $_SERVER['MONGO_DBNAME'] : $database;
See http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

2017-12-23 06:27 UTC, neSpecc requested changes

2017-12-23 06:27 UTC, neSpecc commented on www/schema/types/Mutation.php
> +                            'title'      => Type::nonNull(Type::string()),
ownerId

2017-12-23 06:27 UTC, neSpecc commented on www/schema/types/Query.php
> +                                $user->getFolders($args['foldersLimit'], $args['foldersSkip']);
не проверяется наличие опционального аргумента foldersSkip. А если foldersLimit и foldersSkip не передавать, то folders вообще не вернутся?

2017-12-23 06:27 UTC, neSpecc commented on www/schema/types/User.php
> +                        'description' => 'User\'s email address',
messy

2017-12-23 08:22 UTC, neSpecc approved these changes
excellent 👍

2017-12-23 08:40 UTC, gohabereg approved these changes

2017-12-23 08:41 UTC, merged