Alpha and some improves
codex-team/codex.notes.server pull request #2
Opened 2017-10-15 19:25 UTC by demyashev

2017-10-15 19:29 UTC, demyashev commented on src/models/User.php
> +            return $messages['auth']['userId']['empty'];
Забыл лог ошибки

2017-10-15 19:32 UTC, neSpecc requested changes

2017-10-15 19:32 UTC, neSpecc commented on src/models/User.php
> +                # user init fault
нужно залогировать

2017-10-15 19:32 UTC, neSpecc commented on src/modules/Api.php
> +			$logger->error('API version is not setted');
was not set.

2017-10-15 19:32 UTC, neSpecc commented on src/modules/Api.php
> +        	$this->_response['success'] = FALSE;
проблемы с табуляцией

2017-10-15 19:32 UTC, neSpecc commented on src/modules/Api.php
> +        	$this->_response['code'] = 500;
коды надо вынести в константы

2017-10-15 19:32 UTC, neSpecc commented on src/modules/Auth.php
> +            $localSalt = self::generatePassword();
соль всегда разная?

2017-10-15 19:32 UTC, neSpecc commented on src/modules/Mongo.php
> +        $domain = (is_null($domain)) ? $config['mongodb']['domain'] : $domain;
лишние скобки

2017-10-15 19:49 UTC, talyguryn requested changes

2017-10-15 19:49 UTC, talyguryn commented on README.md
> +curl -X POST --data 'password=qwdqq' http://codex.notes.server/user/create
код надо оборачивать в ```

2017-10-15 19:49 UTC, talyguryn commented on src/config/autoload.php
> +require_once 'auth.php';
очень грязный способ. хитрый, но грязный.

2017-10-15 19:49 UTC, talyguryn commented on src/modules/Api.php
> +			$logger->error('API version is not setted');
API version is missing

2017-10-15 19:49 UTC, talyguryn commented on src/modules/Api.php
> +		$this->_response = [
табы надо убрать

2017-10-15 19:49 UTC, talyguryn commented on src/modules/Api/User.php
> +		$userId = $this->request->getAttribute('userId');
табы

2017-10-15 19:49 UTC, talyguryn commented on src/modules/Log.php
> +		global $config;
табы

2017-10-15 19:49 UTC, talyguryn commented on src/modules/Mongo.php
> +
лог

2017-10-15 19:49 UTC, talyguryn commented on src/public/index.php
> +require '../../vendor/autoload.php';
а нельзя сделать точку входа повыше, чтобы не городить такое?

2017-10-15 19:49 UTC, talyguryn commented on src/public/routes.php
> +$app->post('/{apiVer}/user/get/{userId}', function(Request $request, Response $response) {
пост ли?

2017-10-15 19:49 UTC, talyguryn commented on src/public/routes.php
> +$app->post('/', function(Request $request, Response $response) {
пост?

2017-10-17 17:19 UTC, demyashev commented on src/modules/Auth.php
> +            $localSalt = self::generatePassword();
@neSpecc да, разная. А разве не так задумывалось?

2017-10-17 18:25 UTC, closed without merging