collaborators mutations
codex-team/codex.notes.server pull request #26
Opened 2017-12-31 19:00 UTC by talyguryn

2017-12-31 19:09 UTC, gohabereg requested changes

2017-12-31 19:09 UTC, gohabereg commented on www/components/api/models/Folder.php
> +//        if (!$this->isShared) {
Зачем это?

2017-12-31 19:09 UTC, gohabereg commented on www/schema/types/Mutation.php
> +                                $selectedFields = $info->getFieldSelection();
Это точно надо? Может все подряд заполнять?

2018-01-02 11:16 UTC, neSpecc requested changes

2018-01-02 11:16 UTC, neSpecc commented on www/schema/types/Mutation.php
> +                            $folder = new Folder($args['authorId'], $args['folderId']);
comment

2018-01-02 11:32 UTC, neSpecc requested changes
Поле `email` не обязательно при принятии приглашения

2018-01-02 12:54 UTC, neSpecc approved these changes

2018-01-02 12:58 UTC, gohabereg approved these changes

2018-01-02 12:58 UTC, merged