API systematization
codex-team/codex.notes.server pull request #3
Opened 2017-10-17 18:27 UTC by demyashev

- единый формат ответа API
- ставятся http коды ответов
- логируются все ошибки

2017-10-17 18:38 UTC, neSpecc requested changes

2017-10-17 18:38 UTC, neSpecc commented on src/public/routes.php
> +    $user = new Api\User($request, $response);
а зачем в функцию апи передается реквест и респонс? разве туда не должен передаваться только userId

2017-10-17 18:38 UTC, neSpecc commented on src/modules/Auth.php
> +        return substr(md5(uniqid()), 0, $length);
для пароля лучше не использовать md5

2017-10-17 18:38 UTC, neSpecc commented on src/modules/Auth.php
> +        return substr(md5(uniqid()), 0, $length);
и uniqid

2017-10-17 18:38 UTC, neSpecc commented on src/modules/Auth.php
> +        return substr(md5(uniqid()), 0, $length);
погугли

2017-10-17 18:39 UTC, neSpecc requested changes

2017-10-17 18:39 UTC, neSpecc commented on README.md
> +$ curl -X POST http://codex.notes.server/user/get/89c2633b
где учитывается версия api ?

2017-10-17 18:39 UTC, neSpecc commented on src/models/User.php
> +        $userId = Auth::generatePassword();
user id или пароль?

2017-10-17 18:39 UTC, neSpecc commented on src/models/User.php
> +        $userIdlength = strlen($userId);
userIdLength

2017-10-17 20:09 UTC, demyashev commented on src/modules/Auth.php
> +        return substr(md5(uniqid()), 0, $length);
@neSpecc function getRandomHex($num_bytes=4) {
  return bin2hex(openssl_random_pseudo_bytes($num_bytes));
}

2017-10-17 20:35 UTC, gohabereg requested changes

2017-10-17 20:35 UTC, gohabereg commented on src/config/app.php
> +$config['dir']['root'] = __DIR__ . '/../../';
`$_SERVER['DOCUMENT_ROOT']`

2017-10-17 20:35 UTC, gohabereg commented on src/modules/Auth.php
> +            return FALSE;
Лучше все таки `false`
![image](https://user-images.githubusercontent.com/23050529/31687839-186d7570-b393-11e7-87e2-3dc6e8166ea2.png)

2017-10-17 20:35 UTC, gohabereg commented on src/public/routes.php
> +$app->post('/{apiVer}/user/get/{userId}', function(Request $request, Response $response) {
Для параметров можно добавлять regexp

2017-10-17 20:35 UTC, gohabereg commented on src/modules/Api.php
> +    private function setVersion()
А версионность как-то учитывается?

2017-10-19 16:04 UTC, demyashev commented on src/modules/Auth.php
> +            return FALSE;
@gohabereg  откуда скрин? Почитал бы

2017-10-19 16:14 UTC, demyashev commented on src/modules/Api.php
> +    private function setVersion()
Пока нет

2017-10-19 17:27 UTC, demyashev commented
@neSpecc апрувь

2017-10-23 11:52 UTC, n0str approved these changes
Think it's ready.

2017-10-23 12:01 UTC, neSpecc requested changes

2017-10-23 12:01 UTC, neSpecc commented on public/routes.php
> +    $this->get('/',                   'App\Versions\V1\Controllers\Page:index');
давай `v1` с маленькой буквы

2017-10-24 17:30 UTC, neSpecc approved these changes

2017-10-24 17:45 UTC, gohabereg approved these changes

2017-10-24 17:48 UTC, khaydarov approved these changes

2017-10-24 17:48 UTC, merged