Linux case-insensitive path support
codex-team/codex.notes.server pull request #30
Opened 2018-01-05 21:46 UTC by n0str

## Test

With removed auth middleware

Mutation
```
mutation CreateNewUser($id: ID!, $name: String!, $email: String!) {
  user(id: $id, name: $name, email: $email) {
    id,
    name,
    email
  }
}
```

Query:
```
{
  "id": 1,
  "name": "nostr",
  "email": "nostr@ifmo.su"
}
```

Response:
```
{
  "data": {
    "user": {
      "id": "1",
      "name": "nostr",
      "email": "nostr@ifmo.su"
    }
  }
}
```

2018-01-06 12:42 UTC, neSpecc requested changes

2018-01-06 12:42 UTC, neSpecc commented on www/public/autoload.php
> +spl_autoload_register(function ($classname) {
тут надо продокументировать, как будет работать автолоад

2018-01-06 12:42 UTC, neSpecc commented on www/public/routes.php
> +if (($_ENV['JWT_AUTH'] ?? "TRUE") !== "FALSE") {
`$_SERVER` ?

2018-01-06 12:51 UTC, talyguryn requested changes

2018-01-06 12:51 UTC, talyguryn commented on docs/production-server.md
> +add-apt-repository ppa:ondrej/php
php7 ставится из официальных исходников без дополнительных ппа

2018-01-06 12:51 UTC, talyguryn commented on docs/production-server.md
> +apt-get install php7.1 php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-mysql php7.1-mbstring php7.1-mcrypt php7.1-zip php7.1-fpm
зачем mysql?

2018-01-06 16:08 UTC, n0str commented on www/public/routes.php
> +if (($_ENV['JWT_AUTH'] ?? "TRUE") !== "FALSE") {
Модуль dotenv раскладывает переменные по $_ENV и $_SERVER. Семантически $_ENV наилучшее и очевидное место для этой переменной. Если обращаться к $_SERVER – не сразу очевидно, что это переменная из .env файла.

2018-01-06 16:09 UTC, n0str commented on docs/production-server.md
> +add-apt-repository ppa:ondrej/php
Приведи пример команды?

2018-01-06 19:18 UTC, talyguryn requested changes

2018-01-06 19:18 UTC, talyguryn commented on docs/production-server.md
> +add-apt-repository ppa:ondrej/php
```
root@ubuntu:~# apt install php
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  php-common php7.0 php7.0-cli php7.0-common php7.0-fpm php7.0-json
  php7.0-opcache php7.0-readline
Suggested packages:
  php-pear
The following NEW packages will be installed:
  php php-common php7.0 php7.0-cli php7.0-common php7.0-fpm php7.0-json
  php7.0-opcache php7.0-readline
0 upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 3544 kB of archives.
After this operation, 14.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

2018-01-06 19:18 UTC, n0str commented on docs/production-server.md
> +add-apt-repository ppa:ondrej/php
Это 7.0

2018-01-07 07:29 UTC, neSpecc approved these changes

2018-01-07 13:10 UTC, talyguryn approved these changes

2018-01-07 13:11 UTC, merged