Unit testing v2
codex-team/codex.notes.server pull request #33
Opened 2018-01-08 16:16 UTC by n0str

## Run

```docker exec -it 5614ac800a5d composer test```

```
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.12
Configuration: /var/www/codex.notes.server/phpunit.xml
Error:         No code coverage driver is available

......                                                              6 / 6 (100%)

Time: 1.11 seconds, Memory: 8.00MB

OK (6 tests, 10 assertions)
```

2018-01-08 17:40 UTC, neSpecc requested changes

2018-01-08 17:40 UTC, neSpecc commented on www/tests/helpers/WebTestCase.php
> +        $this->client = new WebTestClient($this->app);
WebTestClient не инклюдится. Откуда он тут?

2018-01-08 17:40 UTC, neSpecc commented on www/versions/v1/controllers/Sync.php
> +<?php
откуда этот файл? давно уже нет папки versions и rest-контроллеров

2018-01-08 17:40 UTC, neSpecc commented on www/tests/StaticWebTest.php
> +class StaticWebTest extends LocalWebTestCase
LocalWebTestCase не надо через use подключить? не понятно откуда он тут

2018-01-08 21:42 UTC, neSpecc requested changes

2018-01-08 21:42 UTC, neSpecc commented on www/tests/GraphQlNaiveTest.php
> +class GraphQlNaiveTest extends LocalWebTestCase
LocalWebTestCase тоже лучше явно через use определить

2018-01-08 21:42 UTC, neSpecc commented on www/tests/bootstrap.php
> +use App\Tests\Helpers\WebTestClient;
тут точно нужны эти use?

2018-01-09 09:13 UTC, n0str commented on www/tests/bootstrap.php
> +use App\Tests\Helpers\WebTestClient;
Они уже лишние. Можно ещё убрать use там, где они совпадают с текущим Namespace вроде как.

2018-01-09 20:35 UTC, neSpecc approved these changes

2018-01-09 20:36 UTC, merged