Check user access
codex-team/codex.notes.server pull request #38
Opened 2018-01-11 17:40 UTC by gohabereg

close #36

2018-01-11 19:40 UTC, neSpecc requested changes

2018-01-11 19:40 UTC, neSpecc commented on www/components/middleware/Auth.php
> +            return $res->withStatus(403, 'Unsupported HTTPAuth type');
цифру надо бы вынести в константу в классе HTTP

2018-01-11 19:40 UTC, neSpecc commented on www/components/middleware/Auth.php
> +    public static function checkUserAccess($userId)
: bool

2018-01-11 19:40 UTC, neSpecc commented on www/schema/types/Mutation.php
> +                                throw new \Exception('Access denied');
надо сделать класс AuthException и отнаследовать его от Exception

2018-01-12 19:28 UTC, neSpecc approved these changes

2018-01-12 19:34 UTC, talyguryn requested changes
😈

2018-01-12 19:34 UTC, talyguryn commented on www/components/middleware/Auth.php
> +            return $res->withStatus(HTTP::CODE_FORBIDDEN, 'Unsupported HTTPAuth type');
сообщение можно вынести в константы класса http

2018-01-12 19:34 UTC, talyguryn commented on www/components/middleware/Auth.php
> +            return $res->withStatus(HTTP::CODE_FORBIDDEN, 'Invalid JWT');
сообщение можно вынести в константы класса http

2018-01-12 19:34 UTC, talyguryn commented on www/schema/types/Mutation.php
> +                                    throw new AuthException('Access denied');
тоже бы в константу вынести, раз повторяется

2018-01-12 20:51 UTC, talyguryn approved these changes

2018-01-12 20:58 UTC, merged