Mailer model
codex-team/codex.notes.server pull request #42
Opened 2018-01-13 19:00 UTC by khaydarov

2018-01-13 19:09 UTC, talyguryn requested changes

2018-01-13 19:09 UTC, talyguryn commented on www/components/base/models/Mailer.php
> +
лишняя строка

2018-01-13 19:09 UTC, talyguryn commented on www/components/base/models/Mailer.php
> +    public static function instance() {
```
public static function instance()
{
```

2018-01-13 19:09 UTC, talyguryn commented on www/components/base/models/Mailer.php
> +     * @param string $subject
описание?

2018-01-13 19:09 UTC, talyguryn commented on www/components/base/models/Mailer.php
> +    public function send(string $subject, array $sendFrom, array $recipients, $body, array $headers = [], array $attachments = []) {
```
public function send(string $subject, array $sendFrom, array $recipients, $body, array $headers = [], array $attachments = []): bool
{
```

2018-01-13 19:09 UTC, talyguryn commented on www/components/base/models/Mailer.php
> +    private function __construct() {
```
private function __construct()
{
```

2018-01-13 19:09 UTC, talyguryn commented on www/components/base/models/Mailer.php
> +        $server = Config::get('MAILER_SERVER') ?? 'localhost';
дефолтные параметры можно вынести в константы

2018-01-15 05:44 UTC, talyguryn requested changes

2018-01-15 05:44 UTC, talyguryn commented on www/components/base/models/Mailer.php
> +
лишняя строка

2018-01-15 06:00 UTC, neSpecc requested changes

2018-01-15 06:00 UTC, neSpecc commented on www/components/base/models/Mailer.php
> +    public function send(string $subject, array $sendFrom, array $recipients, $body, array $headers = [], array $attachments = [])
а recipient не может быть один? это понадобится для транзакционных рассылок. То же самое с sendFrom

2018-01-15 06:00 UTC, neSpecc commented on www/components/base/models/Mailer.php
> +    public function send(string $subject, array $sendFrom, array $recipients, $body, array $headers = [], array $attachments = [])
нужно указать тип возвращаемых данных

2018-01-15 06:00 UTC, neSpecc commented on www/components/base/models/Mailer.php
> +        $message = (new Swift_Message($subject));
лишние скобки?

2018-01-15 20:05 UTC, khaydarov commented on www/components/base/models/Mailer.php
> +    public function send(string $subject, array $sendFrom, array $recipients, $body, array $headers = [], array $attachments = [])
может, параметр $recipient можно указать так ["mail@mail.ru"], либо ["mail@mail.ru" => "MailRUGroup"] или через запятую перечислить несколько

2018-01-15 20:05 UTC, khaydarov commented on www/components/base/models/Mailer.php
> +    public function send(string $subject, array $sendFrom, array $recipients, $body, array $headers = [], array $attachments = [])
тип указан, @return {Boolean}

2018-01-15 20:06 UTC, khaydarov commented on www/components/base/models/Mailer.php
> +        $message = (new Swift_Message($subject));
в документации вроде так создается инстанс

2018-01-16 07:09 UTC, neSpecc commented on www/components/base/models/Mailer.php
> +    public function send(string $subject, array $sendFrom, array $recipients, $body, array $headers = [], array $attachments = [])
> может, параметр $recipient можно указать так ["mail@mail.ru"], либо ["mail@mail.ru" => "MailRUGroup"] или через запятую перечислить несколько

это то понятно. Я имел ввиду что в 99% случаев там будет один адресат, поэтому можно было бы как-то это учесть. Хотя смотри сам, если это усложнит код, то фиг с ним.

2018-01-16 07:11 UTC, neSpecc commented on www/components/base/models/Mailer.php
> +    public function send(string $subject, array $sendFrom, array $recipients, $body, array $headers = [], array $attachments = [])
>тип указан, @return {Boolean}

Мы в этом проекте используем последнюю версию PHP и ее фишки. В том числе [Return type declarations](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.return-type-declarations).

2018-01-16 07:20 UTC, n0str requested changes

2018-01-16 07:20 UTC, n0str commented on www/.env.example
> +// SWIFT MAILER SETTINGS
Не пора подумать над разделением этих настроек на отдельные файлы?

2018-01-16 07:20 UTC, n0str commented on www/components/base/models/Mailer.php
> +                    // send attachment without content-type
Тут должен быть ```Swift_Attachment::fromPath($file);```

2018-01-16 07:20 UTC, n0str commented on www/components/base/models/Mailer.php
> +        $username = Config::get('MAILER_USERNAME') ?? 'admin';
А нужен этот хардкод admin/admin ?

2018-01-16 07:25 UTC, khaydarov commented on www/.env.example
> +// SWIFT MAILER SETTINGS
пора, думаю круто было бы использовать YAML

2018-01-16 07:33 UTC, khaydarov commented on www/components/base/models/Mailer.php
> +        $username = Config::get('MAILER_USERNAME') ?? 'admin';
можно выпилить, это для локали делал. Хотя он нафиг не нужен

2018-01-16 07:34 UTC, khaydarov commented on www/components/base/models/Mailer.php
> +                    // send attachment without content-type
неа, тут ошибка в
```php
if (!is_int($file)) { 
```
типа если file это индекс в массиве, то добавить в аттачмент значение

2018-01-16 07:35 UTC, khaydarov commented on www/components/base/models/Mailer.php
> +                    // send attachment without content-type
поэтому 
```php
!is_int($file)
```

2018-01-16 07:38 UTC, n0str commented on www/.env.example
> +// SWIFT MAILER SETTINGS
Попробуй. мне нравится такой вариант. Можно отдельным реквестом.

2018-01-16 07:38 UTC, n0str commented on www/components/base/models/Mailer.php
> +        $username = Config::get('MAILER_USERNAME') ?? 'admin';
Нужно выпилить

2018-01-16 08:27 UTC, neSpecc requested changes

2018-01-16 08:27 UTC, neSpecc commented on www/components/base/models/Mailer.php
> +        } elseif (is_string($recipients)) {
почему это в секции `// Configure senders` ? запутано получается

2018-01-16 08:27 UTC, neSpecc commented on www/components/base/models/Mailer.php
> +            $message->setFrom($recipients);
почему получатель это `setFrom` ?

2018-01-16 08:27 UTC, neSpecc commented on www/components/base/models/Mailer.php
> +    public function send(string $subject, array $sendFrom, $recipients, $body, array $headers = [], array $attachments = [])
Мы в этом проекте используем последнюю версию PHP и ее фишки. В том числе [Return type declarations](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.return-type-declarations).

2018-01-16 08:27 UTC, neSpecc commented on www/components/base/models/Mailer.php
> +     * Method that send sends a message
send sends?

2018-01-16 08:39 UTC, n0str requested changes

2018-01-16 08:39 UTC, n0str commented on www/components/base/models/Mailer.php
> +                    // send attachment without content-type
Всё-равно, этот код очень запутывает. Переименуй тогда.
Не должно быть ```send attachment without content-type``` и после этого ```Swift_Attachment::fromPath($contentType);```
Если в переменной $contentType содержится тело письма, то и называться оно должно по-другому. Тогда лучше сделать промежуточную
```
foreach($attachments as $file => $payload)
```
и прокомментировать в каком случае оно body, а в каком contentType

2018-01-18 16:25 UTC, khaydarov commented on www/components/base/models/Mailer.php
> +                    // send attachment without content-type
ага, но получается, что все равно если передать как 
```php
['file.png'] 
```
то file будет int, а payload название файла. Универсальное название пока не смог придумать. Можно отказаться от идеи делать в цикле и придумать другой способ

2018-01-18 18:26 UTC, gohabereg requested changes

2018-01-18 18:26 UTC, gohabereg commented on www/components/base/models/Mailer.php
> +    private static $_instance;
Давай без `_`

2018-01-20 08:35 UTC, n0str requested changes

2018-01-20 08:35 UTC, n0str commented on www/config/mailer.sample.php
> +return [
Этот файл не используется и полностью заменён .env

2018-01-20 14:02 UTC, neSpecc approved these changes

2018-01-20 17:38 UTC, n0str approved these changes

2018-01-20 17:46 UTC, talyguryn requested changes
это мерджить нельзя. давайте с этого реквеста научимся использовать psr-fixer

2018-01-20 17:46 UTC, talyguryn commented on www/.gitignore
> +config/mailer.php
?

2018-01-20 17:46 UTC, talyguryn commented on www/components/base/models/Mailer.php
> +
очень большие проблемы с пустыми строками

2018-01-20 18:01 UTC, talyguryn approved these changes

2018-01-20 20:09 UTC, gohabereg approved these changes

2018-01-20 20:14 UTC, merged