set fields
codex-team/codex.notes.server pull request #49
Opened 2018-01-16 17:07 UTC by talyguryn

2018-01-16 18:39 UTC, n0str approved these changes

2018-01-17 10:47 UTC, neSpecc requested changes

2018-01-17 10:47 UTC, neSpecc commented on www/components/base/models/BaseException.php
> +        Log::instance()->debug($message);
This is not a debug level, probably you should use error-level or warning-level

2018-01-17 10:47 UTC, neSpecc commented on www/components/oauth/OAuth.php
> +            'user_id' => $user->id,
Here is the other task

2018-01-17 10:47 UTC, neSpecc commented on www/components/oauth/OAuth.php
> +        if (isset($profileInfo->error)) {
`!empty` would be better

2018-01-17 10:47 UTC, neSpecc commented on www/components/oauth/OAuth.php
> +        Log::instance()->debug('User model from DB: ' . json_encode($user));
`User model from DB ` -> `New user registered`

2018-01-17 10:47 UTC, neSpecc commented on www/components/oauth/OAuth.php
> +        Log::instance()->debug('User model from DB: ' . json_encode($user));
or user updating also handles here?

2018-01-17 10:47 UTC, neSpecc commented on www/components/oauth/OAuth.php
> +//            'google_id' => $userData['google_id'],
are u sure that we don't need this on the client-side?

2018-01-17 10:47 UTC, neSpecc commented on www/public/index.php
> +\Hawk\HawkCatcher::instance(Config::get('HAWK_TOKEN'));
wrap with `!empty(Config::get('HAWK_TOKEN'))`

2018-01-17 10:47 UTC, neSpecc commented on www/schema/types/Mutation.php
> +//                    'user' => [
User mutation will be used to update photos, name and other Settings, that User will made with the Client

2018-01-17 12:00 UTC, actorFromCalifornia approved these changes

2018-01-17 12:58 UTC, neSpecc commented on www/components/middleware/Auth.php
> +            $decoded         = JWT::decode($token, $key, ['HS256']);
лишний отступ

2018-01-17 13:00 UTC, neSpecc approved these changes

2018-01-17 13:01 UTC, neSpecc requested changes
Wait for testing

2018-01-17 13:30 UTC, neSpecc requested changes
[2018-01-17 13:24:24.419692] [warning] JWT is missing
[2018-01-17 13:24:25.494563] [warning] JWT is missing
[2018-01-17 13:24:27.427426] [warning] JWT is missing
[2018-01-17 13:24:35.205452] [warning] JWT is missing
[2018-01-17 13:24:42.080646] [warning] Undefined property: stdClass::$user_id
[2018-01-17 13:24:42.095460] [error] Undefined property: stdClass::$user_id in /var/www/codex.notes.server/public/index.php:59
#0 /var/www/codex.notes.server/Components/Middleware/Auth.php(62): App\{closure}(8, 'Undefined prope...', '/var/www/codex....', 62, Array)
#1 [internal function]: App\Components\Middleware\Auth->jwt(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#2 /var/www/codex.notes.server/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Array, Array)
#3 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#4 /var/www/codex.notes.server/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#5 /var/www/codex.notes.server/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /var/www/codex.notes.server/vendor/slim/slim/Slim/Route.php(313): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /var/www/codex.notes.server/vendor/slim/slim/Slim/App.php(495): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /var/www/codex.notes.server/vendor/akrabat/rka-ip-address-middleware/src/IpAddress.php(93): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 [internal function]: RKA\Middleware\IpAddress->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#10 /var/www/codex.notes.server/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(RKA\Middleware\IpAddress), Array)
#11 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#12 /var/www/codex.notes.server/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#13 /var/www/codex.notes.server/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/codex.notes.server/vendor/slim/slim/Slim/App.php(388): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/codex.notes.server/vendor/slim/slim/Slim/App.php(296): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /var/www/codex.notes.server/public/index.php(94): Slim\App->run()
#17 {main}

2018-01-17 13:59 UTC, neSpecc approved these changes

2018-01-17 14:01 UTC, merged