Docker nginx socket support
codex-team/codex.notes.server pull request #68
Opened 2018-02-03 17:17 UTC by n0str

2018-02-12 14:00 UTC, talyguryn requested changes

2018-02-12 14:00 UTC, talyguryn commented on www/.env.example
>  // Server
можешь дописать коммент попонятнее

2018-02-12 14:06 UTC, talyguryn requested changes

2018-02-12 14:06 UTC, talyguryn commented on www/components/base/tpl/layout.php
> +    <link rel="stylesheet" href="/static/css/codex.css?v=2">
напиши получение версии из времени последнего редактирования файла

2018-02-12 14:06 UTC, talyguryn commented on www/components/sockets/Sockets.php
> +    public static function push($channel, $message) {
пср-фиксер нужен

2018-02-12 14:06 UTC, talyguryn commented on www/public/static/svg/spaceship.svg
> +	<g id="spaceship-wrapper" transform="rotate(-50) translate(0, -50)" fill="#ffffff">
а можно от табов избавиться?

2018-02-13 11:41 UTC, talyguryn approved these changes

2018-02-13 11:48 UTC, gohabereg approved these changes

2018-02-13 15:57 UTC, neSpecc approved these changes

2018-02-13 15:58 UTC, merged