Collaborator Invite mutation
codex-team/codex.notes.server pull request #70
Opened 2018-02-08 10:32 UTC by gohabereg

2018-02-08 10:39 UTC, neSpecc requested changes

2018-02-08 10:39 UTC, neSpecc commented on www/components/api/models/Collaborator.php
> +        $invitedUser = User::find($this->userId);
```php
$invitedUser = new User($this->userId);
$userExists = $invitedUser->exists();
```

2018-02-08 10:39 UTC, neSpecc commented on www/components/api/tpl/email.php
> +Greetings!
tabs

2018-02-11 11:29 UTC, n0str approved these changes

2018-02-19 17:02 UTC, neSpecc requested changes

2018-02-19 17:02 UTC, neSpecc commented on www/components/api/models/Collaborator.php
> +    private function getJoinLink() {
: string

2018-02-19 17:02 UTC, neSpecc commented on www/components/api/models/Base.php
> +    public function exists()
: bool

2018-02-19 17:02 UTC, neSpecc commented on www/schema/types/Query.php
> +                    'collaborator' => [
он вернет только одного? это для чего нужно

2018-02-21 06:25 UTC, talyguryn commented on www/schema/types/Query.php
> +                    'collaborator' => [
мы вообще нигде не используем эти query. только один sync

2018-02-22 16:32 UTC, talyguryn approved these changes

2018-02-22 16:52 UTC, khaydarov requested changes

2018-02-22 16:52 UTC, khaydarov commented on www/components/api/models/Collaborator.php
> +        $invitedUser = new User('', '', $this->email);
А нельзя просто null передавать? Чтобы на пустоту потом не проверять?

2018-02-22 16:52 UTC, khaydarov commented on www/components/api/models/User.php
> +        if (!empty($googleId)) {
А если сюда попадет '      ', что empty вернет? Кажется лучше нул использовать

2018-02-22 17:11 UTC, merged