user mutation
codex-team/codex.notes.server pull request #72
Opened 2018-02-15 15:05 UTC by Nikitos9I

2018-02-19 06:26 UTC, neSpecc requested changes

2018-02-19 06:26 UTC, neSpecc commented on www/schema/types/User.php
> +                    'dtSync' => [
это поле точно нужно?

2018-02-21 06:59 UTC, khaydarov approved these changes

2018-02-21 10:33 UTC, neSpecc requested changes

2018-02-21 10:33 UTC, neSpecc commented on www/components/api/models/User.php
> +    public $dtSync;
это клиентские данные, на сервере хранить не нужно.

2018-02-21 10:42 UTC, talyguryn approved these changes

2018-02-21 11:27 UTC, neSpecc approved these changes

2018-02-21 11:31 UTC, merged