Sender data
codex-team/codex.notes.server pull request #85
Opened 2018-04-11 07:18 UTC by talyguryn

- do not send pushes to yourself
- do not notify users if you send to cloud with dtModify not greater than saved in cloud DB

2018-04-11 07:31 UTC, neSpecc requested changes

2018-04-11 07:31 UTC, neSpecc commented on docs/sockets-channel.md
> +- `folder`
что будет тут?

2018-04-11 07:31 UTC, neSpecc commented on docs/sockets-channel.md
> +- `user`
что будет тут?

2018-04-11 07:31 UTC, neSpecc commented on docs/sockets-channel.md
> +- `folderId`
не указано поле folder

2018-04-11 07:31 UTC, neSpecc commented on www/components/api/models/Collaborator.php
> +        $folder = new Folder($this->folder->ownerId, $this->folder->id);
а нельзя просто `$this->folder` использовать?

2018-04-11 07:31 UTC, neSpecc commented on www/components/api/models/Note.php
> +    public $folder;
а в модели folder текущая заметка будет входить в notes, то есть будет рекурсия

2018-04-11 07:31 UTC, neSpecc commented on www/components/api/models/User.php
> +     * @param object $sender
надо описать тип

2018-04-11 07:31 UTC, neSpecc commented on www/components/notify/Notify.php
> +     * @param        $sender
тип параметра sender

2018-04-11 07:31 UTC, neSpecc commented on www/schema/types/Mutation.php
> +                                $sender = new User($args['ownerId']);
тут должен быть id текущего пользователя, а не овнера

2018-04-11 07:31 UTC, neSpecc commented on www/schema/types/Mutation.php
> +                            $sender = new User($args['authorId']);
id текущего пользователя

2018-04-11 07:31 UTC, neSpecc commented on www/schema/types/Mutation.php
> +                                $sender = new User($args['ownerId']);
id текущего пользователя

2018-04-11 07:31 UTC, neSpecc commented on www/schema/types/Mutation.php
> +                                $sender = new User($args['userId']);
у join нету sender, тк пользователь сам вызвал это событие

2018-04-12 11:48 UTC, neSpecc approved these changes

2018-05-08 12:48 UTC, khaydarov approved these changes

2018-05-08 12:48 UTC, merged